server:
  port: 8080

spring:
  sharding-sphere:
    datasource:
      names: master,slave
      ##主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: root

      ##从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: root











  cache:
    ehcache:
      config: classpath:ehcache.xml

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1s
        max-active: -1
    password:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    ## 确认消息已发送到交换机(Exchange)
    ## publisher-confirms: true
    publisher-confirm-type: correlated
    ## 确认消息已发送到队列(Queue)
    publisher-returns: true

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.mkl.suaggerDemo.model

logging:
  level:
    com.wxw: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
  config: classpath:logback.xml

